### ISSUE TITLE
Setup CircleCI for running Gherkin tests with behave

### ISSUE THREAD

**Issue by johnsBeharry** [peakshift/telegram-dogecoin#4]
```meta
Difficulty: 3
Status: Ready
Reward: 250 Doge
```
```gherkin
Scenario: New commit pushed to develop branch
  Given "telegram-dogecoin" is setup as a project on circleci.com
  When a developer pushes a new commit to the "develop" branch
  Then circle-ci runs a job with the command "behave"
```

#### NOTES

If it is not possible to configure tests to run on a specific branch it will also be acceptable if the tests run on all new commits at the heart pushed to the repository.

Based on current knowledge of the circle-ci configuration this may or may not be possible, so do not cause it to be a blocker.

Resources; https://youtu.be/0OjEx2UzLUI?t=446

**Comment by vindard** [comment]
Just adding as a reference, [this link](https://scotch.io/tutorials/continuous-integration-with-python-and-circle-ci) was helpful for me to understand Continuous Integration and how CircleCI works.
